int (* listOffset)[3];
int (* lists)[2];
int (* cells2)[10];
int * levelOffset;
int (* nodes)[10];
vec3 * centers;
real_t xquad[2*P];
real_t wquad[2*P];
real_t Anm1[(P+1)*(P+2)/2];
real_t Anm2[(P+1)*(P+2)/2];
Cells cells;
